FL-12: create decks screens
FlingoLingo/flingolingo pull request #22
Opened 2023-04-13 14:43 UTC by vshgr

2023-04-13 15:37 UTC, snitsaryuk requested changes

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +        static let deckInfo: String = "Всего слов: 3\nИзучено слов: 2\nПоследний раз повторяли : 10.04.2023"
нужно сделать VStack с 3 текстами, плюс давай тут создадим какую-то ViewModel под данные

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +        static let smallSpacing: CGFloat = 15
нужны общие константы в модуле UIComponents

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckCardView.swift
> +                    .font(Font(Fonts.cardsText))
давай напишем extension на SwiftUI.Font и добавим туда аналогичные как в UIKit

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksScrollView.swift
это не нужно в мейн ветку

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    func placeholder<Content: View>(
подскажи плиз где используется, не увидел

2023-04-13 15:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/WordCardView.swift
> +        static let translation: String = "яблоко"
да, понимаю, что просто UI накидала, но давай сразу добавим domain модельку, на основе которой будет рисоваться вьюха

2023-04-13 15:44 UTC, igor-yndx requested changes

2023-04-13 15:44 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/DecksPageView.swift
> +    enum Constants {
То что переиспользуется во всем прилоджениее лучше вынести в UIComponents

2023-04-13 15:48 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckCardView.swift
> +                    .font(Font(Fonts.cardsText))
окей

2023-04-13 15:48 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksScrollView.swift
почему?

2023-04-13 15:48 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    func placeholder<Content: View>(
TextField .placeholder, чтобы сделать его кастомным

2023-04-13 15:49 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    func placeholder<Content: View>(
`TextField("", text: $text)
                .placeholder(when: text.isEmpty) {
                    Text("Найти слово в колоде...")
                        .font(Font(Fonts.searchText))
                        .foregroundColor(Color(ColorScheme.inactive))
                }
                .foregroundColor(Color(ColorScheme.mainText))`

2023-04-13 15:49 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +        static let mainSpacing: CGFloat = 25
окей

2023-04-13 15:51 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +extension View {
так как на SwiftUI пишем только мы с Яной, возможно, это будет использоваться только 1 раз

2023-04-14 09:48 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/ButtonView.swift
> +    enum Constants {
translation не используется
Давай вообще уберем Constants и buttonText как проперти структуры
И тогда тектст будет передаваться извне
`ButtonView(buttonText: "Начать")`

2023-04-14 09:52 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/ButtonView.swift
> +    enum Constants {
````
struct ButtonView: View {
    
    var buttonText: String
    
    var body: some View {
        Button(action: {
            // TODO: add action
        }, label: {
            Text(buttonText)
                .font(Font(Fonts.buttonTitle))
                .foregroundColor(Color(ColorScheme.mainText))
        })
        .frame(maxWidth: .infinity)
        .padding(.all, CommonConstants.smallSpacing)
        .background(Color(ColorScheme.accent))
        .cornerRadius(CommonConstants.cornerRadius)
    }
}

struct Buttonpr: PreviewProvider {
    static var previews: some View {
        ButtonView(buttonText: "Начать")
    }
}

2023-04-14 14:48 UTC, snitsaryuk requested changes

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +                                   backButtonClicked: {viewModel.backButtonClicked()}, editButtonClicked: {viewModel.editButtonClicked()})
1) с новой строчки свойства в ините
2) можно сделать так: `backButtonClicked: viewModel.backButtonClicked`

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +                ButtonView(buttonText: "Начать") {
заюзать локалайзабл

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +    var editButtonClicked: (() -> Void)?
let

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +    var editButtonClicked: (() -> Void)?
и от опциональности избавиться

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckCardView.swift
> +        Button(action: {
кажется, в action можно засунуть как-то так:
`Button(action: deckCardClicked)`

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksHeaderView.swift
> +    }
локалайзабл

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +        static let cornerRadius: CGFloat = 10
в общие константы

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    private var isTextEmpty: Color {
название свойства не очень удачное, лучше `borderColor` или что-то вроде такого

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksPageView.swift
> +    @StateObject private var viewModel = DecksViewModel(decks: Array(repeating: Deck(id: 1, title: "Для путешествий", wordsCount: 100, learnedWords: 32, repetitionDate: Date.now, cards: []), count: 5
должно снаружи сеттаться

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/Utilities/Formatter.swift
> +        "Всего слов: \(deck.wordsCount)"
локалайзбал

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +    }
методы всегда под инитом

2023-04-14 14:48 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +public class DeckViewModel: ObservableObject {
final class

2023-04-15 10:37 UTC, snitsaryuk requested changes

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +    var deck: Deck
`private let`

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +    @State private var text: String = ""
вынести во viewModel

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +    var deck: Deck
должно лежать во vm

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/ButtonView.swift
> +    let buttonClicked: (() -> Void)
private

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +    let editButtonClicked: (() -> Void)
private

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +                Button(action: backButtonClicked,
давай все вьюхи переделаем в таком виде:
`Button(action: backButtonClicked) {
// UI
}`

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckCardView.swift
> +    var deckCardClicked: (() -> Void)
private let

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckInfoView.swift
> +    var deck: Deck
up + private

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksHeaderView.swift
> +            Text(NSLocalizedString("decksHeader", comment: ""))
попробуй просто ключ передать, должно норм показаться

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksHeaderView.swift
> +    private let viewModel = DecksHeaderViewModel()
должно снаружи сеттаться

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    @Binding var text: String
лучше vm создать

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/WordCardView.swift
> +    var wordCardClicked: (() -> Void)
private let

2023-04-15 10:37 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/Factories/DecksViewControllerFactory.swift
> +    @ObservedObject private var viewModel = DecksViewModel()
должно приходить в `func decksViewController`

2023-04-15 11:39 UTC, snitsaryuk requested changes

2023-04-15 11:39 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckBackHeaderView.swift
> +    private let deck: Deck
вроде, используется только `.title`, давай в ините принимать текст

2023-04-15 11:39 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DecksHeaderView.swift
> +            Text(LocalizedStringKey("decksHeader"))
попробуй просто ключ передать
Text("decksHeader")

2023-04-15 11:39 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +    @Binding var text: String
private

2023-04-15 11:39 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/SearchView.swift
> +                    Text(LocalizedStringKey("searchWordInDeckPlaceholder"))
попробуй просто ключ передать

2023-04-15 11:39 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/Utilities/Formatter.swift
> +struct Formatter {
давай дадим нейминг другой, DeckFormatter, могут появиться другие форматтеры

2023-04-15 12:15 UTC, snitsaryuk approved these changes

2023-04-15 12:16 UTC, igor-yndx commented on FlingoLingo/Modules/Package.swift
> +		.target(
странные отступы

2023-04-15 12:25 UTC, igor-yndx approved these changes

2023-04-15 12:29 UTC, snitsaryuk approved these changes

2023-04-15 12:55 UTC, merged