Fl 14
FlingoLingo/flingolingo pull request #31
Opened 2023-04-14 15:34 UTC by kidjuniper

2023-04-15 12:18 UTC, snitsaryuk requested changes
нужно тебе создать пакет в модуле spm, как ребята

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/ViewController.swift
> +
убрать изменения

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/SelectedLanguages/Language.swift
> +class Language: UIButton {
не нужна кастомная кнопка, удалить

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/SelectedLanguages/Arrow.swift
> +class Arrow: UIButton {
не нужна кастомная вьюха, удалить

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +class DictionaryTableViewCell: UITableViewCell {
final class

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +    var word = UILabel()
`word -> wordLabel`

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +    var word = UILabel()
private let

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +    }
не нужно

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +        contentView.frame = contentView.frame.inset(by: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0))
верстаем на констрейнтах

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +    func cellSettings() {
private configureCell

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +        word.text = "Слово"
текст приходит снаружи

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +
отступы убрать

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DictionaryTableViewCell.swift
> +        word.font = UIFont(name: "Furuta Bold", size: 15)
брать из общей дизайн системы

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DTableFuncs.swift
удалить файл, вынести extension в viewController

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DTableFuncs.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "DTableViewCell", for: indexPath) as! DictionaryTableViewCell
избавиться от force unwrap

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DTableFuncs.swift
> +    }
надо сверстать ячейку так, чтобы само растягивалось, высоту не хардкодим

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DTableFuncs.swift
> +           cell.layer.mask = maskLayer
скругление в настройках ячейки делаем

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DictTableView/DTableFuncs.swift
> +    }
почему 40?

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +class clearView: UIView {
названия класса с большой буквы

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +        placeholder = "Введите слово..."
в локалайзбал должно быть

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +    @objc func clear() {
private

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +        let rw = clearView()
rw не ок название, нужно чуть детальнее

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DViews/.DS_Store
не удалил файл

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +class DictionaryViewController: UIViewController, UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource {
final class

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +class DictionaryViewController: UIViewController, UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource {
реализацию протоколов вынести в extensions

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        // шрифт потом общий
уже нужен общий, подтяни мейн себе

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        topLabel.text = "Словарь"
должно быть в локалайзабл

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +    open var tableSpacing = 10
зачем open var? нужно избавиться от этого свойства

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +    }()
не нужно тут держать реквест

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +    private lazy var networkFetcher: NetworkFetcher = {
где реализация фетчера?

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        //networkFetcher.getLangs(result: fen2(_:))
убрать ненужное

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        let suggestionViewConstraint = suggestionView.topAnchor.constraint(equalTo: originLanguage.bottomAnchor, constant: 25)
использовать константы из модуля

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +
отступы убрать и выше

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        NSLayoutConstraint.activate([self.arrowConstraint!, self.suggestionViewConstraint!])
не надо force unwrap

2023-04-15 12:18 UTC, snitsaryuk commented on FlingoLingo/DictionaryScreen/Constants.swift
файл уже есть в мейне, подтяни изменения

2023-04-15 12:48 UTC, igor-yndx requested changes

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/Constants.swift
> +        self.topPadding = screenHeight * 0.09
Должны быть фиксированные отступы, а не % от высоты и ширины

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        tableView.translatesAutoresizingMaskIntoConstraints = false
Уже выше есть

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        tableView.delegate = self
тоже выше уже выставляется delegate

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        topLabel.font = UIFont(name: "Futura Bold", size: 32)
Это по дизайну?

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        topLabel.textColor = .white
Цвет нужно взять из ColorScheme

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +class DTextField: UITextField {
final
И не понятно что за префикс 'D'
Нужно дать понятное название классу

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +        layer.borderColor = UIColor.white.cgColor
Цвет из ColorScheme

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +        layer.cornerRadius = Constants().screenWidth * 0.025
Скругление должно быть фиксированным, а не % от ширины

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +class clearView: UIView {
Класс вынести в отдельный файл и final или сделать private

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +        self.addSubview(button)
self явно не нужно тут писать

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +    open var suggest = ""
Почему `open`?

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DViews/DTextField.swift
> +class SuggestionView: UIButton {
Кажется не нужен тут subclass, прочто конфигурируется кнопка

2023-04-15 12:48 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        NSLayoutConstraint.activate(topLabelConstraints)
Вместо нескольких вызовов нужно сделать 1
`NSLayoutConstraint.activate([
])`

2023-04-15 13:07 UTC, igor-yndx commented on FlingoLingo/DictionaryScreen/DController(s)/DictionaryViewController.swift
> +        view.backgroundColor = .init(red: 0.15, green: 0.15, blue: 0.15, alpha: 1)
Цвет из ColorScheme

2023-04-17 07:04 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Dictionary/DViews/DictTableView/DTableFuncs.swift
> +        return tableView.frame.height / 8
высота ячейки должна быть фиксированной, а не зависеть от высоты фрейма

2023-04-17 07:04 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Dictionary/DViews/DictTableView/DictionaryTableViewCell.swift
> +class DictionaryTableViewCell: UITableViewCell {
final

2023-04-17 07:04 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Dictionary/DViews/DictTableView/DictionaryTableViewCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
убрать

2023-04-17 07:04 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Dictionary/DViews/SelectedLanguages/Language.swift
> +class Language: UIButton {
`final class LanguageButton`

2023-04-17 11:08 UTC, igor-yndx approved these changes

2023-04-17 11:21 UTC, yanawishnya approved these changes

2023-04-17 11:26 UTC, snitsaryuk approved these changes

2023-04-17 11:26 UTC, merged