FL-26: screens profile and password change added
FlingoLingo/flingolingo pull request #32
Opened 2023-04-14 15:43 UTC by yanawishnya

все отступы - хардкод, жду поступления CommonContstants

2023-04-15 07:41 UTC, igor-yndx commented
Много ворнингов от линтера
Можно запустить  `Pods/SwiftLint/swiftlint --fix` чтобы пофиксить автоматом

2023-04-15 07:46 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/UserProfile/UserProfileView.swift
> +        static let email: String = "hello@world.ru"
Лучше сразу сделать ViewModel и из нее брать данные

2023-04-15 07:46 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/UserProfile/GuestProfileView.swift
> +
лишний перенос

2023-04-15 07:46 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/UserProfile/ChangePasswordView.swift
> +        static let email: String = "hello@world.ru"
Тоже лучше вынести в ViewModel

2023-04-15 07:46 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/UserProfile/Components/StatisticsView.swift
> +    enum Constants {
Тоже ViewModel

2023-04-15 11:02 UTC, snitsaryuk requested changes

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/ChangePasswordViewControllerFactory.swift
> +    @ObservedObject private var viewModel = UsersViewModel()
не нужно тут, надо принимать в методе changePasswordViewController

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/GuestProfileViewControllerFactory.swift
> +    @ObservedObject private var viewModel = UsersViewModel()
аналогично

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/UserProfileViewControllerFactory.swift
> +    @ObservedObject private var viewModel = UsersViewModel()
аналогично

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/UserProfileViewControllerFactory.swift
> +class UserProfileViewControllerFactory {
struct везде + public

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Models/User.swift
> +//    public let isAuthorized: Bool
комменты не нужно держать

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Models/User.swift
> +    public var timesRepeated: Int?
let

2023-04-15 11:02 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UsersViewModel.swift
> +class UsersViewModel: ObservableObject {
final class

2023-04-15 13:00 UTC, snitsaryuk requested changes

2023-04-15 15:31 UTC, yanawishnya commented on FlingoLingo/Modules/Sources/UserProfile/Components/ButtonView.swift
> +    let buttonClicked: (() -> Void)
тогда я не смогу передавать экшн на кнопку извне

2023-04-15 15:53 UTC, snitsaryuk requested changes

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UIComponents/PasswordTextField.swift
> +    public let placeholder: String
private кажется нужен

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Components/BubbleView.swift
> +    private var bubbleText: String
let

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Components/ButtonView.swift
> +    private var buttonText: String
let

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/ChangePasswordViewControllerFactory.swift
> +    public func changePasswordViewController(viewModel: UserViewModel) -> UIViewController {
viewModel убрать из параметра

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Models/User.swift
> +                wordsLearned: Int = 0, decksCount: Int = 0, timesRepeated: Int = 0) {
с новой строчки каждую переменную

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +    public func comparePasswords() -> Bool {
лучше isPasswordEquals

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +        return false
можно return newPassword == confirmPassword

2023-04-15 15:53 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Utlities/ProfileFormatter.swift
убрать простые строчки

2023-04-17 07:17 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +            print(newPassword)
print стоит убрать

2023-04-17 07:17 UTC, igor-yndx commented on FlingoLingo/SceneDelegate.swift
> +        let navigationConroller = UINavigationController(rootViewController: ChangePasswordViewControllerFactory()
Нужно убрать перед мержем

2023-04-17 08:33 UTC, igor-yndx commented on FlingoLingo/SceneDelegate.swift
> +        let navigationConroller = UINavigationController(rootViewController: ChangePasswordViewControllerFactory()
Экран профиля можно уже вставить в TabController

2023-04-17 12:37 UTC, yanawishnya commented on FlingoLingo/Modules/Sources/UserProfile/Utlities/ProfileFormatter.swift
> +        if user.daysOfUse % 10 == 1 {
это сарказм да...

2023-04-17 13:26 UTC, snitsaryuk requested changes

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +            validatePasswords[.old] = "Пароль должен состоять как минимум  из 6 символов"
локалайзбал

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +public final class UserViewModel: ObservableObject {
убрать по файлу public

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +            validatePasswords[.new] = ""
лучше nil сеттать

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +    }
просто сравниваем по ==

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +    }
отдельный метод не нужен

2023-04-17 13:26 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +    public func isPasswordCorrect(password: String?) -> Bool {
private func, приватные функции унести в самый низ класса

2023-04-17 15:25 UTC, snitsaryuk requested changes

2023-04-17 15:25 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +    @Published var confirmPasswordCorrect: Bool = true
убрать эти поля

2023-04-18 07:21 UTC, igor-yndx commented on FlingoLingo/Modules/Package.swift
> +				"Dictionary"
большой оступ появился

2023-04-18 07:30 UTC, snitsaryuk approved these changes

2023-04-18 10:51 UTC, vshgr approved these changes

2023-04-18 10:53 UTC, merged