Fl 46
FlingoLingo/flingolingo pull request #49
Opened 2023-04-17 16:38 UTC by reatlaz

доделал AuthClass и ProfileClass
пооддержку keychain в сетевом слое решили добавить потом, сделаю таску
На текущем этапе разработки токен берется из InternalConstants.swift и вставляются туда разработчиком вручную

2023-04-18 07:14 UTC, igor-yndx requested changes

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/DeckClient.swift
> +    struct Deck: Decodable {
public

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/DeckClient.swift
> +    enum DecksError: Error {
public

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/ProfileClient.swift
> +class ProfileClient {
final

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/ProfileClient.swift
> +        // request.setValue(APP_FILE_NAME, forHTTPHeaderField: "User-Agent")
удалить

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/ProfileClient.swift
> +        request.httpBody = try! JSONSerialization.data(withJSONObject: ["old_password": oldPassword, "new_password": newPassword]) /* else {
Есть `JSONEncoder`, лучше его использовать, по аналогии с `JSONDecoder`

2023-04-18 07:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/ProfileClient.swift
> +        // request.setValue(APP_FILE_NAME, forHTTPHeaderField: "User-Agent")
удалить

2023-04-18 07:14 UTC, igor-yndx commented on Podfile
> -
Изменений в Podfile и Podfile.lock не должно быть

2023-04-18 08:14 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/AuthClient.swift
> +
Лишние отступы

2023-04-18 08:52 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/ProfileClient.swift
> +public final class ProfileClient {
Получается много дублируемого кода
Там 
Было бы круто вынести хождегние в сеть в отдельную ф-цию
Там отличие только в httpMethod, body и типе ответа
Можно тут использовать generic
```
func makeRequest<T: Decodable>(method:, body:,  completion: @escaping (Result<T, ProfileError>) {
  ...
  JSONDecoder().decode(T.self, from: data)
  ...

}
```

2023-04-18 08:52 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/DeckClient.swift
> +        request.httpBody = try! JSONSerialization.data(withJSONObject: ["name": name, "description": description, "is_private": isPrivate] as [String : Any])
Сразу не увидел, нужно везде использовать JSONEncoder вместо JSONSerialization

2023-04-18 08:53 UTC, igor-yndx commented on Podfile.lock
> -PODFILE CHECKSUM: 9647a6c7b5e6649b15917ddefd64c5c9be675f1d
Здесь тоже нужно вернуть как было

2023-04-18 08:57 UTC, igor-yndx commented
Нужно поправить ошибки от линтера

2023-04-18 09:06 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/CardClient.swift
> +        request.setValue("Token \(token)", forHTTPHeaderField: "Authorization")
token лучше передать явно в init и сохранить, а не использовать глобальный константный

В DeckClient тоже самое

2023-04-19 15:58 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/NetworkLayer/NetworkLayer.swift
> +        print(String(data: data, encoding: .utf8)!)
print убрать

2023-04-19 15:58 UTC, igor-yndx commented on Podfile.lock
> -COCOAPODS: 1.12.0
Тоже не должно измениться

2023-04-19 16:16 UTC, igor-yndx approved these changes

2023-04-19 16:17 UTC, xandermuratov approved these changes

2023-04-19 16:17 UTC, merged