FL-41: add cards screen
FlingoLingo/flingolingo pull request #58
Opened 2023-04-18 18:13 UTC by xandermuratov

2023-04-18 20:06 UTC, snitsaryuk requested changes

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +            )
не очень нравится идея с NotificationCenter, можно завести Subject, на который можно будет подписаться и слушать элементы

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +                flashcardRotation -= 180
180 вынести в константы класса хотя бы

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardsNavigationBarView.swift
> +
а почему пустой экшен?

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsView.swift
> +    func doSwipe(rightSwipe: Bool = false) {
через буль не очень хорошо, а если завтра будем добавлять свайп вверх? лучше завести `enum Direction`

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/Factories/CardsViewControllerFactory.swift
> +public struct CardsViewControllerFactory {
не нужен public, так как флоу внутри модуля

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/View Models/CardsViewModel.swift
> +class CardsViewModel: ObservableObject {
final class

2023-04-18 20:06 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/View Models/CardsViewModel.swift
> +    func getCardsCount() -> Int {
не нужная функция, можем напрямую обратиться

2023-04-19 09:27 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardsNavigationBarView.swift
> +
нужно завести экшен во viewModel и тут его вызывать

2023-04-19 16:55 UTC, snitsaryuk requested changes

2023-04-19 16:55 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +    private var card: Card
должно во viewModel лежать

2023-04-19 16:55 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +    }
вынести в начало класса

2023-04-19 16:55 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +                    viewModel.displayingCards.removeFirst()
надо сделать у vm метод removeFirst(), чтобы вьюха была глупой

2023-04-19 16:55 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +extension View {
private extension

2023-04-19 17:46 UTC, xandermuratov commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +    private var card: Card
Я же в CardsView циклом прохожусь по массиву с displayingCards и для каждого элемента создаю отдельную CardView(viewModel: viewModel, card: card) со своим значением card, то есть в каждой CardView лежит своя card, к которой я обращаюсь, как я могу их поместить во viewModel и из каждой CardView обращаться к своей card? Может как есть оставить?

2023-04-19 17:49 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/CardsComponents/CardView.swift
> +    private var card: Card
по-хорошему тут должна быть своя vm, но да, давай так оставим, не крит

2023-04-19 17:53 UTC, snitsaryuk approved these changes

2023-04-19 17:54 UTC, yanawishnya approved these changes

2023-04-19 17:54 UTC, merged