FL-59: merged UserProfileView and GuestView
FlingoLingo/flingolingo pull request #60
Opened 2023-04-18 18:20 UTC by yanawishnya

2023-04-18 20:07 UTC, snitsaryuk requested changes

2023-04-18 20:07 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Components/GuestView.swift
> +        Text(NSLocalizedString("guest", comment: ""))
можно просто ключ передать в Text

2023-04-18 20:07 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ProfileView.swift
> +    @ObservedObject var viewModel: UserViewModel
private

2023-04-18 20:07 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ProfileView.swift
> +    @State var isGuest: Bool
должно быть внутри vm

2023-04-19 07:07 UTC, vshgr approved these changes

2023-04-19 09:28 UTC, igor-yndx submitted a review, later dismissed

2023-04-19 09:33 UTC, snitsaryuk requested changes

2023-04-19 09:33 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/ChangePasswordViewControllerFactory.swift
> +        let viewModel = UserViewModel(user: user, backAction: backAction, isGuest: false)
не надо сеттать в ините, viewModel будет обращаться к какому-нибудь AccountProvider и получать информацию по аккаунту

2023-04-19 09:33 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ProfileRouter.swift
> +public final class ProfileRouter {
кажется public не нужен

2023-04-19 09:33 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ProfileView.swift
> +    public init(viewModel: UserViewModel) {
не нужен public

2023-04-19 09:33 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
>           backAction: @escaping () -> Void = {},
давай уберем отсюда user и у backAction дефолтное значение, можно по невнимательности не передать его и тогда не будет работать переход

2023-04-19 09:33 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/UserViewModel.swift
> +         router: ProfileRouter = ProfileRouter(),
тут тоже давай уберем дефолтное значение

2023-04-19 10:08 UTC, snitsaryuk commented
конфликтик(

2023-04-19 11:16 UTC, snitsaryuk requested changes

2023-04-19 11:16 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/Factories/ChangePasswordViewControllerFactory.swift
> +        let viewModel = UserViewModel(user: user, backAction: backAction, router: ProfileRouter())
тут кажется вообще роутер не нужен, тут просто backAction

2023-04-19 11:27 UTC, yanawishnya commented on FlingoLingo/Modules/Sources/UserProfile/Factories/ChangePasswordViewControllerFactory.swift
> +        let viewModel = UserViewModel(user: user, backAction: backAction, router: ProfileRouter())
а как тогда, я же убрала дефолтное значение из параметров, я должна как-то передать роутер, нил передавать?

2023-04-19 12:20 UTC, snitsaryuk requested changes

2023-04-19 12:20 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/ChangePasswordViewModel.swift
> +public final class ChangePasswordViewModel: ObservableObject {
public не нужен

2023-04-19 12:20 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/ProfileViewModel.swift
> +public final class ProfileViewModel: ObservableObject {
public не нужен

2023-04-19 12:20 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/UserProfile/ViewModels/ProfileViewModel.swift
> +        router.changePassword(user: self.user)
бещ self.

2023-04-19 12:58 UTC, snitsaryuk approved these changes

2023-04-19 13:15 UTC, merged