FL-66: deckProvider and methods initialized
FlingoLingo/flingolingo pull request #70
Opened 2023-04-19 17:28 UTC by vshgr

2023-04-19 18:22 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/DecksComponents/DeckCardView.swift
> +        if deck.cards.count == 0 {
`deck.cards.isEmpty`

2023-04-19 18:22 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/DecksPageView.swift
> +                viewModel.provider.getAllDecks { result in
Нужно внутри viewModel сделать метод `reloadDeckes` и там все обновлять
provider закрыть private

2023-04-19 18:22 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/View Models/DecksViewModel.swift
> +    let provider: DecksProvider
private

2023-04-19 18:25 UTC, snitsaryuk requested changes

2023-04-19 18:25 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/Protocol/DecksProtocolImpl.swift
> +public class DecksProtocolImpl: DecksProvider {
DecksProviderImpl

2023-04-19 18:25 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/DeckView.swift
> +                                         wordCardClicked: { viewModel.wordCardClicked() },
`wordCardClicked: viewModel.wordCardClicked`

2023-04-19 18:50 UTC, snitsaryuk reviewed
все ок, надо сеть теперь добавить

2023-04-19 18:50 UTC, snitsaryuk commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +    let provider: DecksProvider
private

2023-04-19 21:42 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
Конвертацию Response -> DomainDeck нужно делать внутри provider

2023-04-19 21:50 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
пока не очень понимаю как,  я пока просто результат прикидываю

```
public func getDeck(id: Int, onFinish: @escaping (Result<DeckResponse, ClientError>) -> Void) {
        let client = DeckClient(token: "00fa7675354ab19839cdd317efa545429764b77e")
        client.getDeck(id: id, completion: { result in
            DispatchQueue.main.async {
                onFinish(result)
            }
        })
    }

2023-04-19 21:52 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
сделать у фукнции возвращаемое значение? deck и внутри функции тогда катить как я сейчас во вьюмодели делаю?

2023-04-19 21:53 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
но тогда зачем нужен onFinish в параметрах..

2023-04-19 22:08 UTC, vshgr commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
ладно, примерно понимаю, завтра уточню уже

2023-04-20 07:02 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/View Models/DeckViewModel.swift
> +                self?.deck = DomainDeck(deckResponse: deck)
Идея в том что пользователь DecksProvider получает сразу доменную модель, коневертация происходит внутри
Нужно добавить доменную ошибку DecksError
И обновить все методы DecksProvider
```
enum DecksError: Error {
    case client(ClientError)
}

public protocol DecksProvider: AnyObject {
    func getAllDecks(onFinish: @escaping (Result<[DomainDeck], DecksError>) -> Void)
}

public func getAllDecks(onFinish: @escaping (Result<[DomainDeck], DecksError>) -> Void) {
    let client = DeckClient(token: "00fa7675354ab19839cdd317efa545429764b77e")
    client.getDecks { result in
        DispatchQueue.main.async {
            switch result {
            case .success(let deckResponse):
                onFinish(.success(DomainDeck(deckResponse: deckResponse))
            case .failure(let clientError):
                onFinish(.client(clientError))
            }
        }
    }
}
```

2023-04-20 07:02 UTC, igor-yndx commented on FlingoLingo/Modules/Sources/Decks/Protocol/DecksProviderImpl.swift
> +        let client = DeckClient(token: "00fa7675354ab19839cdd317efa545429764b77e")
Везде повторяется токен. Давай вынесем в computed property чтобы потом легче подставить настоящее значение

2023-04-20 08:04 UTC, igor-yndx approved these changes

2023-04-20 08:05 UTC, snitsaryuk approved these changes

2023-04-20 08:21 UTC, merged