FL-5: Umbrella package added
FlingoLingo/flingolingo pull request #9
Opened 2023-04-12 15:48 UTC by yanawishnya

2023-04-12 15:52 UTC, vshgr commented on FlingoLingo/.DS_Store
Delete

2023-04-12 15:52 UTC, vshgr requested changes
Delete .DS_Store

2023-04-12 15:54 UTC, vshgr approved these changes

2023-04-12 18:06 UTC, snitsaryuk commented
сообщения коммита должны быть вида "FL-5: <что сделано>", нужно поменять

2023-04-13 11:17 UTC, snitsaryuk approved these changes

2023-04-13 11:19 UTC, vshgr approved these changes

2023-04-13 11:20 UTC, merged